@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam ParticipantPadding 0

box Logic LOGIC_COLOR_T1
participant ":AddPointsCommandParser" as AddPointsCommandParser LOGIC_COLOR
participant "p:Points" as Points LOGIC_COLOR
participant "a:AddPointsCommand" as AddPointsCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "alice:Person" as Person LOGIC_COLOR
participant "m:Model" as Model MODEL_COLOR
end box

[-> AddPointsCommandParser : parse(\n"n/Alice \np/50")
activate AddPointsCommandParser

create Points
AddPointsCommandParser -> Points
activate Points

Points --> AddPointsCommandParser : p
deactivate Points

create AddPointsCommand
AddPointsCommandParser -> AddPointsCommand : AddPointsCommand(...)
activate AddPointsCommand

AddPointsCommand --> AddPointsCommandParser : a
deactivate AddPointsCommand

[<-- AddPointsCommandParser : a
deactivate AddPointsCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
[<-[hidden]- AddPointsCommandParser
destroy AddPointsCommandParser

[-> AddPointsCommand : execute(m)
activate AddPointsCommand

AddPointsCommand -> Model : getFilteredPersonList()
activate Model

Model --> AddPointsCommand : fpl
deactivate Model

alt "Alice" matches name in fpl
    AddPointsCommand -> Person : addPoints(p)
activate Person

Person --> AddPointsCommand
deactivate Person

create CommandResult
AddPointsCommand -> CommandResult
activate CommandResult

CommandResult --> AddPointsCommand
deactivate CommandResult

[<-- AddPointsCommand : r

else
    [<-- AddPointsCommand : commandException
end
@enduml
